export enum ChatIntent {
  BOOK_FIELD = 'BOOK_FIELD',
  SEARCH_FIELD = 'SEARCH_FIELD',
  CHECK_AVAILABLE = 'CHECK_AVAILABLE',
  SEARCH_BY_DISTRICT = 'SEARCH_BY_DISTRICT',
  SEARCH_BY_PRICE = 'SEARCH_BY_PRICE',
  SEARCH_BY_TIME = 'SEARCH_BY_TIME',
  SEARCH_BY_DATE = 'SEARCH_BY_DATE',
  CHECK_BOOKING = 'CHECK_BOOKING',
  FAQ = 'FAQ',
  GREETING = 'GREETING',
  UNKNOWN = 'UNKNOWN',
}
